version: '3.7'
services:
  buzzvel-api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    stdin_open: true
    tty: true
    hostname: buzzvel-api
    ports:
      - 80:80
      - 9002:9002
    volumes:
      - "../app:/home/deploy/apps/php7"
    command:
      - 'nginx -g "daemon off;"'
    networks:
      buzzvel-api:
        ipv4_address: 172.48.6.7
    depends_on:
      - buzzvel-api-mysql
  buzzvel-api-mysql:
    image: mysql:8.0.19
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - "mysql.env"
    volumes:
      - "./mysql/scripts/buzzvle_api.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      buzzvel-api:
        aliases:
          - "mysql.buzzvel-api.development"
        ipv4_address: 172.48.6.8


networks:
  buzzvel-api:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 172.48.6.0/24